openapi: 3.0.2
info:
    title: lxkns
    version: 0.16.0
    description: 'Discover Linux-kernel namespaces, almost everywhere in a Linux host.'
    contact:
        url: 'https://github.com/thediveo/lxkns'
    license:
        name: Apache 2.0
        url: 'https://www.apache.org/licenses/LICENSE-2.0'
servers:
    -
        url: /api
        description: lxkns as-a-service
paths:
    /processes:
        summary: Process discovery
        get:
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ProcessTable'
                    description: |-
                        Returns information about all processes and their position within the process
                        tree.
            summary: Linux processes
            description: |-
                Map of all processes in the process tree, with the keys being the PIDs in
                decimal string format.
    /pidmap:
        summary: Discover the translation of PIDs between PID namespaces
        get:
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/PIDMap'
                    description: |-
                        The namespaced PIDs of processes. For each process, the PIDs in their PID
                        namespaces along the PID namespace hierarchy are returned.
            summary: PID translation data
            description: |
                Discovers the PIDs that processes have in different PID namespaces,
                according to the hierarchy of PID namespaces.

                > **IMPORTANT:** The order of processes is undefined. However, the order of
                > the namespaced PIDs of a particular process is well-defined.
    /namespaces:
        summary: Namespace discovery (includes process discovery for technical reasons)
        get:
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/DiscoveryResult'
                    description: The discovered namespaces and processes.
            summary: Linux kernel namespaces
            description: |-
                Information about the Linux-kernel namespaces and how they relate to processes
                and vice versa.
components:
    schemas:
        PIDMap:
            title: Root Type for PIDMap
            description: |-
                A "map" of the PIDs of processes in PID namespaces for translating a specific
                PID from one PID namespace into another PID namespace.

                > **IMPORTANT:** The order of *processes* is undefined. However, the order of
                > the namespaced PIDs of a particular process is well-defined: from the PID in
                > the process' own PID namespace up the hierarchy to the PID in the initial
                > PID namespace.

                The PID map is represented in a "condensed" format, which is designed to
                minimize transfer volume. Consuming applications thus might want to transfer
                this external representation into a performance-optimized internal
                representation, optimized for translating PIDs.
            type: array
            items:
                $ref: '#/components/schemas/NamespacedPIDs'
            example:
                -
                    -
                        pid: 12345
                        nsid: 4026531905
                    -
                        pid: 1
                        nsid: 4026538371
                -
                    -
                        pid: 666
                        nsid: 4026538371
        NamespacedPID:
            title: Root Type for NamespacedPID
            description: |-
                A process identifier (PID) valid only in the accompanying PID namespace,
                referenced by the ID (inode number) of the PID namespace. Outside that PID
                namespace the PID is invalid and might be confused with some other process that
                happens to have the same PID in the other PID namespace. For instance, PID 1
                can be found not only in the initial PID namespace, but usually also in all
                other PID namespaces, but referencing completely different processes each time.
            required:
                - pid
                - nsid
            type: object
            properties:
                pid:
                    description: a process identifier
                    type: integer
                nsid:
                    format: int64
                    description: |-
                        a PID namespace identified and referenced by its inode number (without any
                        device number).
                    type: integer
            example:
                pid: 1
                nsid: 4026531905
        NamespacedPIDs:
            description: |-
                The list of namespaced PIDs of a process, ordered according to the PID
                namespace hierarchy the process is in. The order is from the "bottom-most" PID
                namespace a particular process is joined to up to the initial PID namespace.
                Thus, the PID in the initial PID namespace always comes last.
            type: array
            items:
                $ref: '#/components/schemas/NamespacedPID'
            example:
                -
                    pid: 12345
                    nsid: 4026531905
                -
                    pid: 1
                    nsid: 4026532382
        Process:
            description: |-
                Information about a specific process, such as its PID, name, and command line
                arguments, the references (IDs) of the namespaces the process is joined to.
            required:
                - pid
                - ppid
                - name
                - cmdline
                - starttime
                - namespaces
                - cpucgroup
                - fridgecgroup
                - fridgefrozen
            type: object
            properties:
                pid:
                    format: int32
                    description: The process identifier (PID) of this process.
                    type: integer
                ppid:
                    format: int32
                    description: |-
                        The PID of the parent process, or 0 if there is no parent process. On Linux, the
                        only processes without a parent are the initial process PID 1 and the PID 2
                        kthreadd kernel threads "process".
                    type: integer
                name:
                    description: |-
                        A synthesized name of the process:
                        - a name set by the process itself,
                        - a name derived from the command line of the process.
                    type: string
                cmdline:
                    description: |-
                        The command line arguments of the process, including the process binary file
                        name. Taken from /proc/$PID/cmdline, see also
                        [https://man7.org/linux/man-pages/man5/proc.5.html](proc(5)).
                    type: array
                    items:
                        type: string
                starttime:
                    format: int64
                    description: |-
                        The time this process started after system boot and expressed in clock ticks.
                        It is taken from /proc/$PID/stat, see also
                        [https://man7.org/linux/man-pages/man5/proc.5.html](proc(5)).
                    type: integer
                cpucgroup:
                    description: |-
                        The (CPU) cgroup (control group) path name in the hierarchy this process is in. The
                        path name does not specify the root mount path of the complete hierarchy, but
                        only the (pseudo) absolute path starting from the root of the particular (v1) or
                        unified (v2) cgroup hierarchy.
                    type: string
                namespaces:
                    $ref: '#/components/schemas/NamespacesSet'
                    description: |-
                        References the namespaces this process is joined to, in form of the namespace
                        IDs (inode numbers).
                fridgecgroup:
                    description: The freezer cgroup path name in the hierarchy this process is in.
                    type: string
                fridgefrozen:
                    description: The effective freezer state of this process.
                    type: boolean
            example:
                namespaces:
                    mnt: 4026531840
                    cgroup: 4026531835
                    uts: 4026531838
                    ipc: 4026531839
                    user: 4026531837
                    pid: 4026531836
                    net: 4026531905
                pid: 1
                ppid: 0
                name: systemd
                cmdline:
                    - /sbin/init
                    - fixrtc
                    - splash
                starttime: 0
                cpucgroup: /init.scope
        ProcessTable:
            description: |-
                Information about all processes in the process tree, with each process item
                being keyed by its PID in string form. Besides information about the process
                itself and its position in the process tree, the processes also reference the
                namespaces they are currently joined to.
            type: object
            additionalProperties:
                $ref: '#/components/schemas/Process'
            example:
                '1':
                    namespaces:
                        mnt: 4026531840
                        cgroup: 4026531835
                        uts: 4026531838
                        ipc: 4026531839
                        user: 4026531837
                        pid: 4026531836
                        net: 4026531905
                    pid: 1
                    ppid: 0
                    name: systemd
                    cmdline:
                        - /sbin/init
                        - fixrtc
                        - splash
                    starttime: 0
                    cpucgroup: /init.scope
                '137024':
                    namespaces:
                        mnt: 4026532517
                        cgroup: 4026531835
                        uts: 4026531838
                        ipc: 4026531839
                        user: 4026532518
                        pid: 4026531836
                        net: 4026531905
                    pid: 137024
                    ppid: 1
                    name: upowerd
                    cmdline:
                        - /usr/lib/upower/upowerd
                    starttime: 3132568
                    cpucgroup: /system.slice/upower.service
        DiscoveryResult:
            description: |-
                The discovered namespaces and processes with their mutual relationships, and
                optionally PID translation data.
            required:
                - namespaces
                - processes
            type: object
            properties:
                processes:
                    $ref: '#/components/schemas/ProcessTable'
                    description: 'Information about all processes, including the process hierarchy.'
                namespaces:
                    $ref: '#/components/schemas/NamespacesDict'
                    description: Map of namespaces.
                pidmap:
                    $ref: '#/components/schemas/PIDMap'
                    description: Data for translating PIDs between different PID namespaces.
                options:
                    description: The options specified for discovery.
            example:
                discovery-options:
                    skipped-procs: false
                    skipped-tasks: false
                    skipped-fds: false
                    skipped-bindmounts: false
                    skipped-hierarchy: false
                    skipped-ownership: false
                    skipped-freezer: false
                    scanned-namespace-types:
                        - time
                        - mnt
                        - cgroup
                        - uts
                        - ipc
                        - user
                        - pid
                        - net
                namespaces:
                    '4026531835':
                        nsid: 4026531835
                        type: cgroup
                        owner: 4026531837
                        reference: /proc/2/ns/cgroup
                        leaders:
                            - 2
                            - 1
                    '4026531836':
                        nsid: 4026531836
                        type: pid
                        owner: 4026531837
                        reference: /proc/2/ns/pid
                        leaders:
                            - 2
                            - 1
                        children:
                            - 4026532338
                    '4026531837':
                        nsid: 4026531837
                        type: user
                        reference: /proc/1/ns/user
                        leaders:
                            - 1
                            - 2
                        children:
                            - 4026532518
                        user-id: 0
                    '4026531838':
                        nsid: 4026531838
                        type: uts
                        owner: 4026531837
                        reference: /proc/2/ns/uts
                        leaders:
                            - 2
                            - 1
                    '4026531839':
                        nsid: 4026531839
                        type: ipc
                        owner: 4026531837
                        reference: /proc/2/ns/ipc
                        leaders:
                            - 2
                            - 1
                    '4026532268':
                        nsid: 4026532268
                        type: mnt
                        owner: 4026531837
                        reference: /proc/1761/ns/mnt
                        leaders:
                            - 1761
                    '4026532324':
                        nsid: 4026532324
                        type: uts
                        owner: 4026531837
                        reference: /proc/1781/ns/uts
                        leaders:
                            - 1781
                    '4026532337':
                        nsid: 4026532337
                        type: ipc
                        owner: 4026531837
                        reference: /proc/33536/ns/ipc
                        leaders:
                            - 33536
                    '4026532340':
                        nsid: 4026532340
                        type: net
                        owner: 4026531837
                        reference: /proc/33536/ns/net
                        leaders:
                            - 33536
                    '4026532398':
                        nsid: 4026532398
                        type: pid
                        owner: 4026531837
                        reference: /proc/34110/ns/pid
                        leaders:
                            - 34110
                        parent: 4026532338
                    '4026532400':
                        nsid: 4026532400
                        type: net
                        owner: 4026531837
                        reference: /proc/34110/ns/net
                        leaders:
                            - 34110
                    '4026532517':
                        nsid: 4026532517
                        type: mnt
                        owner: 4026531837
                        reference: /proc/137024/ns/mnt
                        leaders:
                            - 137024
                    '4026532518':
                        nsid: 4026532518
                        type: user
                        reference: /proc/137024/ns/user
                        leaders:
                            - 137024
                        parent: 4026531837
                        user-id: 0
                processes:
                    '1':
                        namespaces:
                            mnt: 4026531840
                            cgroup: 4026531835
                            uts: 4026531838
                            ipc: 4026531839
                            user: 4026531837
                            pid: 4026531836
                            net: 4026531905
                        pid: 1
                        ppid: 0
                        name: systemd
                        cmdline:
                            - /sbin/init
                            - fixrtc
                            - splash
                        starttime: 0
                        cpucgroup: /init.scope
                    '17':
                        namespaces:
                            mnt: 4026531840
                            cgroup: 4026531835
                            uts: 4026531838
                            ipc: 4026531839
                            user: 4026531837
                            pid: 4026531836
                            net: 4026531905
                        pid: 17
                        ppid: 2
                        name: migration/1
                        cmdline:
                            - ''
                        starttime: 0
                        cpucgroup: ''
                    '1692':
                        namespaces:
                            mnt: 4026532246
                            cgroup: 4026531835
                            uts: 4026532247
                            ipc: 4026531839
                            user: 4026531837
                            pid: 4026531836
                            net: 4026531905
                        pid: 1692
                        ppid: 1
                        name: systemd-timesyn
                        cmdline:
                            - /lib/systemd/systemd-timesyncd
                        starttime: 2032
                        cpucgroup: /system.slice/systemd-timesyncd.service
        Namespace:
            description: |-
                Information about a single Linux-kernel namespace. Depending on the extent of
                the discovery, not all namespace types might have been discovered, or data might
                be missing about the PID and user namespace hierarchies as well as which user
                namespace owns other namespaces.

                For more details, please see also:
                https://man7.org/linux/man-pages/man7/namespaces.7.html.
            required:
                - type
                - nsid
            type: object
            properties:
                nsid:
                    format: int64
                    description: |-
                        Identifier of this namespace: an inode number.

                        - lxkns only uses the inode number in the API, following current Linux kernel
                          and CLI tool practise, which generally identify individual namespaces only by
                          inode numbers (and leaving out the device number).
                        - Namespace identifiers are not UUIDs, but instead reused by the kernel after a
                          namespace has been destroyed.
                    type: integer
                type:
                    $ref: '#/components/schemas/NamespaceType'
                    description: Type of this namespace.
                owner:
                    format: int64
                    description: The ID of the owning user namespace.
                    type: integer
                reference:
                    description: |-
                        File system reference to the namespace, if available. The hierarchical PID and
                        user namespaces can also exist without any file system references, as long as
                        there are still child namespaces present for such a PID or user namespace.
                    type: string
                leaders:
                    description: |-
                        List of PIDs of "leader" processes joined to this namespace.

                        Instead of listing all processes joined to this namespace, lxkns only lists the
                        "most senior" processes: these processes are the highest processes in the
                        process tree still joined to a namespace. Child processes also joined to this
                        namespace can then be found using the child process relations from the process
                        table information.
                    type: array
                    items:
                        format: int32
                        type: integer
                ealdorman:
                    format: int32
                    description: PID of the most senior leader process joined to this namespace.
                    type: integer
                parent:
                    format: int64
                    description: 'Only for PID and user namespaces: the ID of the parent namespace.'
                    type: integer
                user-id:
                    description: |-
                        Only for user namespaces: the UID of the Linux user who created this user
                        namespace.
                    type: integer
                user-name:
                    description: |-
                        Only for user namespaces: the name of the Linux user who created this user
                        namespace.
                    type: string
                children:
                    description: 'For user and PID namespaces: the list of child namespace IDs.'
                    type: array
                    items:
                        format: int64
                        type: integer
                possessions:
                    description: 'Only user namespaces: list of namespace IDs of owned (non-user) namespaces.'
                    type: array
                    items:
                        format: int64
                        type: integer
            example:
                '4026532338':
                    nsid: 4026532338
                    type: pid
                    owner: 4026531837
                    reference: /proc/33536/ns/pid
                    leaders:
                        - 33536
                    parent: 4026531836
                    children:
                        - 4026532398
        NamespaceType:
            description: |-
                Type of Linux-kernel namespace. For more information about namespaces, please
                see also: https://man7.org/linux/man-pages/man7/namespaces.7.html.
            enum:
                - cgroup
                - ipc
                - net
                - mnt
                - pid
                - user
                - uts
                - time
            type: string
            example: '"net"'
        NamespacesDict:
            description: |
                "Map" of Linux-kernel namespaces, keyed by their namespace IDs in stringified
                form. Contrary to what the term "namespace" might suggest, namespaces do not
                have names but are identified by their (transient) inode numbers.

                > **Note:** following current best practice of the Linux kernel and CLI tools,
                > namespace references are only in the form of the inode number, without the
                > device number.

                For further details, please see also:
                https://man7.org/linux/man-pages/man7/namespaces.7.html.
            type: object
            additionalProperties:
                $ref: '#/components/schemas/Namespace'
            example:
                '4026532267':
                    nsid: 4026532267
                    type: mnt
                    owner: 4026531837
                    reference: /proc/1714/ns/mnt
                    leaders:
                        - 1714
                '4026532268':
                    nsid: 4026532268
                    type: mnt
                    owner: 4026531837
                    reference: /proc/1761/ns/mnt
                    leaders:
                        - 1761
        DiscoveryOptions:
            title: Root Type for DiscoveryOptions
            description: ''
            required:
                - scanned-namespace-types
            type: object
            properties:
                skipped-procs:
                    type: boolean
                skipped-tasks:
                    type: boolean
                skipped-fds:
                    type: boolean
                skipped-bindmounts:
                    type: boolean
                skipped-hierarchy:
                    type: boolean
                skipped-ownership:
                    type: boolean
                skipped-freezer:
                    description: |-
                        true if the discovery of the (effective) freezer states of processes has been
                        skipped, so that all processes always appear to be "thawed" (running).
                    type: boolean
                scanned-namespace-types:
                    description: |-
                        List of namespace types included in the discovery. This information might help
                        consuming tools to understand which types of namespaces were scanned and which
                        were not scanned for at all.
                    type: array
                    items:
                        $ref: '#/components/schemas/NamespaceType'
            example:
                skipped-procs: false
                skipped-tasks: false
                skipped-fds: false
                skipped-bindmounts: false
                skipped-hierarchy: false
                skipped-ownership: false
                skipped-freezer: false
                scanned-namespace-types:
                    - time
                    - mnt
                    - cgroup
                    - uts
                    - ipc
                    - user
                    - pid
                    - net
        NamespacesSet:
            description: |-
                The set of 7 namespaces (8 namespaces since Linux 5.6+) every process is always
                joined to. The namespaces are referenced by their IDs (inode numbers):
                - cgroup namespace
                - IPC namespace
                - network namespace
                - mount namespace
                - PID namespace
                - user namespace
                - UTS namespace
                - time namespace (Linux kernel 5.6+)

                > **Note:** Since lxkns doesn't officially support Linux kernels before 4.9
                > all namespaces except the "time" namespace can safely be assumed to be
                > always present.

                For more details about namespaces, please see also:
                https://man7.org/linux/man-pages/man7/namespaces.7.html.
            type: object
            properties:
                cgroup:
                    format: int64
                    description: |-
                        References a cgroup namespace by ID (inode number). Please see also:
                        https://www.man7.org/linux/man-pages/man7/cgroup_namespaces.7.html.
                    type: integer
                ipc:
                    format: int64
                    description: |-
                        References an IPC namespace by ID (inode number). Please see also:
                        https://www.man7.org/linux/man-pages/man7/ipc_namespaces.7.html.
                    type: integer
                net:
                    format: int64
                    description: |-
                        References a network namespace by ID (inode number). Please see also:
                        https://www.man7.org/linux/man-pages/man7/network_namespaces.7.html.
                    type: integer
                mnt:
                    format: int64
                    description: |-
                        References a mount namespace by ID (inode number). Please see also:
                        https://www.man7.org/linux/man-pages/man7/mount_namespaces.7.html.
                    type: integer
                pid:
                    format: int64
                    description: |-
                        References a PID namespace by ID (inode number). Please see also:
                        https://www.man7.org/linux/man-pages/man7/pid_namespaces.7.html.
                    type: integer
                user:
                    format: int64
                    description: |-
                        References a user namespace by ID (inode number). Please see also:
                        https://www.man7.org/linux/man-pages/man7/user_namespaces.7.html.
                    type: integer
                uts:
                    format: int64
                    description: |-
                        References a UTS (*nix timesharing system) namespace by ID (inode number).
                        Please see also: https://www.man7.org/linux/man-pages/man7/uts_namespaces.7.html.
                    type: integer
                time:
                    format: int64
                    description: |-
                        References a (monotonous) time namespace by ID (inode number). Time namespaces
                        are only supported on Linux kernels 5.6 or later. Please see also:
                        https://www.man7.org/linux/man-pages/man7/time_namespaces.7.html.
                    type: integer
            example:
                mnt: 4026531840
                cgroup: 4026531835
                uts: 4026531838
                ipc: 4026531839
                user: 4026531837
                pid: 4026531836
                net: 4026531905
